name: Code Quality Checks

on:
  push

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install direnv
        run: sudo apt-get update && sudo apt-get install -y direnv

      - name: Run quality checks
        shell: bash
        run: |
          cp .env.example .env
          direnv allow
          just code-quality
